# Generated by Django 4.2.24 on 2025-09-17 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='direccion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='venta',
            name='fecha_entrega',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='tipo',
            field=models.CharField(choices=[('FISICA', 'Física / Mostrador'), ('PEDIDO', 'Pedido / Con despacho')], default='FISICA', max_length=10),
        ),
        migrations.AlterField(
            model_name='venta',
            name='cantidad',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='venta',
            name='cliente',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='venta',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
